### PR TITLE
fixed all warnings

### LINKED ISSUE #45: Fix terminal warnings

### PR DESCRIPTION
**Pull request by superstephan1**
closes #45

### CODE REVIEW

File: src/components/Web3/ConnectionCheck.tsx [hunk 1]
```diff
@@ -22,12 +18,12 @@ import {
 
 export const Connect = async () => {
   await connectWeb3();
-  console.log("connected");
+  // console.log("connected");
```
Comment (Rowin206) [inline src/components/Web3/ConnectionCheck.tsx:21]: You can delete those console.log, instead of comments :)

File: src/pages/Worlds.tsx [hunk 2]
```diff
@@ -1,14 +1,14 @@
 import worldsData from '../assets/data/courseinfo.json';
 import Card from "../components/Card";
-import {useLocation} from "react-router-dom";
+// import {useLocation} from "react-router-dom";
```
Comment (Rowin206) [inline src/pages/Worlds.tsx:3]: Comment can be deleted

File: src/pages/Worlds.tsx [hunk 3]
```diff
@@ -1,14 +1,14 @@
...
 import Button from "../components/Button";
 import store from 'store';
 
 export const Worlds = () => {
     const data = worldsData;
     const allowed = ['blockchain', 'tdfa01', 'datascience01', 'programmingdapps01', 'introduction'];
     const continueLearning = store.get('lastWatched');
-    const location = useLocation();
+    // const location = useLocation();
```
Comment (Rowin206) [inline src/pages/Worlds.tsx:11]: Comment can be deleted

**Review by Rowin206 — CHANGES_REQUESTED** [review]
A few small things that can be deleted instead of a comment

**Review by Rowin206 — APPROVED** [review]
